flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: git@github.com:haskoin/haskoin
    commit: 3f2b04cc735f5fb78a9338031d6bf7e86bd4de7c
  subdirs:
  - haskoin-core
  extra-dep: true
extra-deps: []
resolver: lts-7.2
