flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: git@github.com:haskoin/haskoin
    commit: 3f2b04cc735f5fb78a9338031d6bf7e86bd4de7c
  subdirs:
  - haskoin-core
  extra-dep: true
extra-deps:
- murmur3-1.0.2
- pbkdf-1.1.1.1
- secp256k1-0.4.6
- text-1.2.2.1
- yaml-0.8.17.2
resolver: lts-6.4
