flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/haskoin/haskoin.git
    commit: 7730c8c070a8d71b16c4df9c2637881ac47878e3
  subdirs:
  - haskoin-core
  extra-dep: true
extra-deps:
  - murmur3-1.0.3
  - pbkdf-1.1.1.1
  - secp256k1-0.4.8
resolver: lts-8.13
